name: Full
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName
        with:
          tagRegex: "v(.*)"
      - name: Build image
        run: docker build --build-arg "VERSION=${{ steps.tagName.outputs.tag }}" -t vanflux/connect-pharmacy-discord-bot .
      - name: Transfer docker image over ssh
        run: |
              eval $(ssh-agent -s)
              echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
              docker save vanflux/connect-pharmacy-discord-bot | ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker load"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd ~/services && ./deploy-connect-pharmacy-discord-bot.sh
